engines: 
  eslint:
    enabled: true
    config:
      config: ./.eslintrc.json
      extensions:
        - .es6
        - .js
        - .jsx
checks: 
  import/extensions:
    enabled: false
  similar code:
    enabled: false
exclude_paths: 
  - tests/
  - public/
