const adminEmail = 'mark@mark.com';
const adminPassword = '123456';

module.exports = {
  'Documents Pagination': (browser) => {
    browser
      .maximizeWindow()
      .url('http://localhost:8000/')
      .waitForElementVisible('body', 5000)
      .setValue('input[name=email]', adminEmail)
      .setValue('input[name=password]', adminPassword)
      .click('#loginbutton')
      .waitForElementVisible('h3[id="dashboard"]', 5000)
      .assert.urlEquals(`${'http://localhost:8000/dashboard'}`)
      .waitForElementVisible('a[href="document/private"]', 5000)
      .click('a[href="document/private"]')
      .waitForElementVisible('.main-container', 5000)
      .waitForElementVisible('.rc-pagination-item-active', 5000)
      .assert.containsText('.rc-pagination-item-active > a', '1')
      .waitForElementVisible('.rc-pagination-next', 2000)
      .click('.rc-pagination-next')
      .pause(2000)
      .waitForElementVisible('.main-container', 5000)
      .waitForElementVisible('.rc-pagination-item-active', 5000)
      .assert.containsText('.rc-pagination-item-active > a', '2')
      .waitForElementVisible('.rc-pagination-next', 2000)
      .click('.rc-pagination-next')
      .pause(2000)
      .waitForElementVisible('.main-container', 5000)
      .waitForElementVisible('.rc-pagination-item-active', 5000)
      .assert.containsText('.rc-pagination-item-active > a', '3')
      .waitForElementVisible('.rc-pagination-prev', 2000)
      .click('.rc-pagination-prev')
      .pause(2000)
      .waitForElementVisible('.main-container', 5000)
      .waitForElementVisible('.rc-pagination-item-active', 5000)
      .assert.containsText('.rc-pagination-item-active > a', '2')
      .waitForElementVisible('.rc-pagination-prev', 2000)
      .click('.rc-pagination-prev')
      .pause(2000);
  },
  'Users Pagination': (browser) => {
    browser
      .url('http://localhost:8000/')
      .waitForElementVisible('body', 5000)
      .assert.urlEquals(`${'http://localhost:8000/dashboard'}`)
      .waitForElementVisible('a[href="/all-users"]', 5000)
      .assert.visible('a[href="/all-users"]')
      .pause(1000)
      .click('a[href="/all-users"]')
      .waitForElementVisible('h3.user__number', 5000)
      .waitForElementVisible('.rc-pagination-item-active', 5000)
      .assert.containsText('.rc-pagination-item-active > a', '1')
      .waitForElementVisible('.rc-pagination-next', 2000)
      .click('.rc-pagination-next')
      .pause(2000)
      .waitForElementVisible('h3.user__number', 5000)
      .waitForElementVisible('.rc-pagination-item-active', 5000)
      .assert.containsText('.rc-pagination-item-active > a', '2')
      .waitForElementVisible('.rc-pagination-next', 2000)
      .click('.rc-pagination-next')
      .pause(2000)
      .waitForElementVisible('h3.user__number', 5000)
      .waitForElementVisible('.rc-pagination-item-active', 5000)
      .assert.containsText('.rc-pagination-item-active > a', '3')
      .waitForElementVisible('.rc-pagination-prev', 2000)
      .click('.rc-pagination-prev')
      .pause(2000)
      .waitForElementVisible('h3.user__number', 5000)
      .waitForElementVisible('.rc-pagination-item-active', 5000)
      .assert.containsText('.rc-pagination-item-active > a', '2')
      .waitForElementVisible('.rc-pagination-prev', 2000)
      .click('.rc-pagination-prev')
      .pause(2000)
      .end();
  },
};
