export const AJAX_CALL_START = 'AJAX_CALL_START';
export const AJAX_CALL_END = 'AJAX_CALL_END';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const DEAUTHENTICATE_USER = 'DEAUTHENTICATE_USER';

export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_NEW_DOCUMENT = 'ADD_NEW_DOCUMENT';
export const VIEW_EXISTING_DOCUMENT = 'VIEW_EXISTING_DOCUMENT';
