export const AJAX_CALL_START = 'AJAX_CALL_START';
export const AJAX_CALL_END = 'AJAX_CALL_END';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const DEAUTHENTICATE_USER = 'DEAUTHENTICATE_USER';

export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_NEW_DOCUMENT = 'ADD_NEW_DOCUMENT';
export const GET_DOCUMENT_DETAILS = 'GET_DOCUMENT_DETAILS';
export const UPDATE_EXISTING_DOCUMENT = 'UPDATE_EXISTING_DOCUMENT';
export const DELETE_EXISTING_DOCUMENT = 'DELETE_EXISTING_DOCUMENT';

export const GET_PUBLIC_DOCUMENTS = 'GET_PUBLIC_DOCUMENTS';
export const GET_ROLE_DOCUMENTS = 'GET_ROLE_DOCUMENTS';
export const SEARCH_FOR_DOCUMENTS = 'SEARCH_FOR_DOCUMENTS';
